name: Build Web App
  
on:
  push:
    branches:
      - master
      - release/*
  
jobs:
  build:
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
    
      # master - Zip using branch name and build number (example: referencing the version file the build will be packaged as 1.0.1.build_number)
    - name: Zip using version file and build number
      if: github.ref == 'refs/heads/master'
      env:
        version: ''
        build_version: ''
      run: |
        Set-Variable -Name version -Value Get-Content -Path "${{ github.workspace }}\version"
        Set-Variable -Name build_version -Value "${version}.${{ github.run_number }}"
        echo "path: ${{ github.workspace }}\version"
        echo "version: ${version}"
        echo "build_version: ${build_version}"
        Compress-Archive -Path ${{ github.workspace }}/README.md -DestinationPath ${{ github.workspace }}/versioning_${build_version}v1.zip
    
      # release/0.0.0 - Zip using branch name and build number (example: release/1.0.2 will be packaged as 1.0.2.build_number)
    - name: Zip using branch name and build number
      if: contains(github.ref, 'release')
      run: |
        def base_version = ${{ github.ref }}.Substring(8)
        def build_version = "${base_version}.${{ github.run_number }}"
        Compress-Archive -Path ${{ github.workspace }}/README.md -DestinationPath ${{ github.workspace }}/versioning_${build_version}v2.zip
    
    # - name: Upload Zip
    #   run:  cmd /c curl -u ${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_KEY }} -T ${{ github.workspace }}/versioning_${build_version}.*.zip "https://${{ secrets.ARTIFACTORY_KEY }}/artifactory/${{ secrets.ARTIFACTORY_PATH }}"
